### PR TITLE
use player ability lib, so that other mods flights don't constantly get disabled

### PR DESCRIPTION
**Pull request by unix-supremacist**

### CODE REVIEW

**Review by Leclowndu93150 — APPROVED** [review]
yes

**Comment by Laith471** [comment]
Thanks for the PR but I have one question could you tell me what is the mod that has been disabled?

**Comment by unix-supremacist** [comment]
any mod touching the creative flight ability will be disabled with the original code, i specifically noticed it disabling flight with my mod [alchemist](https://github.com/unix-supremacist/Alchemist) which doesn't have a public build yet

**Comment by Leclowndu93150** [comment]
> Thanks for the PR but I have one question could you tell me what is the mod that has been disabled?

Mini Utilities angel rings also don't work

**Comment by Laith471** [comment]
The good news is I fixed it without using the Lib. I just wanna let you know that you helped me
Thanks.

**Pull request closed without merging**
